package main

import (
	_ "github.com/aerosystems/subs-service/docs" // docs are generated by Swag CLI, you have to import it.
	"github.com/aerosystems/subs-service/internal/models"
	"github.com/labstack/echo/v4"
	echoSwagger "github.com/swaggo/echo-swagger"
)

func (app *Config) NewRouter() *echo.Echo {
	e := echo.New()

	docsGroup := e.Group("/docs")
	docsGroup.Use(app.basicAuthMiddleware.BasicAuthMiddleware)
	docsGroup.GET("/*", echoSwagger.WrapHandler)

	e.GET("/v1/subscriptions", app.baseHandler.GetSubscriptions, app.oauthMiddleware.AuthTokenMiddleware(models.CustomerRole))
	e.POST("/v1/subscriptions", app.baseHandler.CreateSubscription, app.oauthMiddleware.AuthTokenMiddleware(models.CustomerRole))
	e.PATCH("/v1/subscriptions/:id", app.baseHandler.UpdateSubscription, app.oauthMiddleware.AuthTokenMiddleware(models.CustomerRole))
	e.DELETE("/v1/subscriptions/:id", app.baseHandler.DeleteSubscription, app.oauthMiddleware.AuthTokenMiddleware(models.CustomerRole))
	return e
}
