package main

import (
	_ "github.com/aerosystems/subs-service/docs" // docs are generated by Swag CLI, you have to import it.
	middleware "github.com/aerosystems/subs-service/internal/middleware"
	"github.com/labstack/echo/v4"
	echoSwagger "github.com/swaggo/echo-swagger"
)

func (app *Config) NewRouter() *echo.Echo {
	e := echo.New()

	docsGroup := e.Group("/docs")
	docsGroup.Use(middleware.BasicAuthMiddleware)
	docsGroup.GET("/*", echoSwagger.WrapHandler)

	e.GET("/v1/subscriptions", app.baseHandler.GetSubscriptions, middleware.AuthTokenMiddleware([]string{"user", "staff"}))
	e.POST("/v1/subscriptions", app.baseHandler.CreateSubscription, middleware.AuthTokenMiddleware([]string{"staff"}))
	e.PATCH("/v1/subscriptions/:id", app.baseHandler.UpdateSubscription, middleware.AuthTokenMiddleware([]string{"staff"}))
	e.DELETE("/v1/subscriptions/:id", app.baseHandler.DeleteSubscription, middleware.AuthTokenMiddleware([]string{"staff"}))
	return e
}
